---
esphome:
  name: garage-relay

esp8266:
  board: esp12e
  early_pin_init: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  platform: esphome

logger:
  baud_rate: 0
  logs:
    sensor: DEBUG

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: 'Sonoff S31 Button'
    on_press:
      - switch.toggle: relay
  - platform: status
    name: 'Sonoff S31 Status'

sensor:
  - platform: wifi_signal
    name: 'Sonoff S31 WiFi Signal'
    update_interval: 60s
  - platform: cse7766
    current:
      name: 'Sonoff S31 Current'
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    voltage:
      name: 'Sonoff S31 Voltage'
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    power:
      name: 'Sonoff S31 Power'
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 60s
    energy:
      name: 'Sonoff S31 Energy'
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power:
      name: 'Sonoff S31 Apparent Power'
      filters:
        - throttle_average: 60s
    power_factor:
      name: 'Sonoff S31 Power Factor'
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s

  - platform: total_daily_energy
    name: 'Sonoff S31 Daily Energy'
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: 'Sonoff S31 Relay'
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF

time:
  - platform: sntp
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: true
