---
esphome:
  name: garage-relay

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  platform: esphome

logger:
  baud_rate: 0
  logs:
    sensor: DEBUG

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_1_relay

light:
  - platform: binary
    name: 'Shelly 1 Light'
    output: shelly_1_relay
    id: lightid

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: 'Switch Shelly 1'
    on_state:
      then:
        - light.toggle: lightid
    internal: true
    id: switchid
