---
substitutions:
  name: garage-relay
  friendly_name: Garage Relay
  area: Garage
  static_ip: 192.168.137.1

packages:
  - !include common/base.yml
  - !include common/wifi.yml
  - !include common/shelly.yml

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_1_relay

switch:
  - platform: output
    name: 'Garage Relay'
    output: shelly_1_relay
    id: garage_relay
    on_turn_on:
      - delay: 1s
      - switch.turn_off: garage_relay
