---
substitutions:
  name: kitchen-lamp
  friendly_name: Kitchen Lamp
  area: Kitchen
  static_ip: 192.168.137.4

packages:
  - !include common/base.yml
  - !include common/wifi.yml
  - !include common/sonoff-s31.yml
