---
substitutions:
  name: living-Room-lamp
  friendly_name: Living Room Lamp
  area: Living Room
  static_ip: 192.168.137.5

packages:
  - !include common/base.yml
  - !include common/wifi.yml
  - !include common/sonoff-s31.yml

light:
  - platform: binary
    name: '${friendly_name}'
    output: relay
