---
substitutions:
  name: sprinkler-controller
  friendly_name: Sprinkler Controller
  area: Backyard
  static_ip: 192.168.137.6

packages:
  - !include common/base.yml
  - !include common/wifi.yml
  - !include common/time.yml

esp32:
  variant: esp32
  framework:
    type: esp-idf

status_led:
  pin:
    number: 23

sprinkler:
  - id: sprinkler_controller
    main_switch: Main
    auto_advance_switch: Auto Advance
    reverse_switch: Reverse
    multiplier_number: Multiplier
    repeat_number: Repeat
    valve_overlap: 5s
    valves:
      - valve_switch: North Side
        enable_switch: Enable North Side
        run_duration_number: North Side Run Duration
        valve_switch_id: relay_1

      - valve_switch: Front
        enable_switch: Enable Front
        run_duration_number: Front Run Duration
        valve_switch_id: relay_2

      - valve_switch: Backyard North
        enable_switch: Enable Backyard North
        run_duration_number: Backyard North Run Duration
        valve_switch_id: relay_4

      - valve_switch: Backyard South
        enable_switch: Enable Backyard South
        run_duration_number: Backyard South Run Duration
        valve_switch_id: relay_5

      - valve_switch: Backyard Sitting Area
        enable_switch: Enable Backyard Sitting Area
        run_duration_number: Backyard Sitting Area Run Duration
        valve_switch_id: relay_6

      - valve_switch: Backyard South Tree
        enable_switch: Enable Backyard South Tree
        run_duration_number: Backyard South Tree Run Duration
        valve_switch_id: relay_7

switch:
  - platform: gpio
    pin: GPIO32
    name: Relay 1
    id: relay_1
    internal: true

  - platform: gpio
    pin: GPIO33
    name: Relay 2
    id: relay_2
    internal: true

  - platform: gpio
    pin: GPIO26
    name: Relay 4
    id: relay_4
    internal: true

  - platform: gpio
    pin: GPIO27
    name: Relay 5
    id: relay_5
    internal: true

  - platform: gpio
    pin: GPIO14
    name: Relay 6
    id: relay_6
    internal: true

  - platform: gpio
    pin: GPIO12
    name: Relay 7
    id: relay_7
    internal: true
