---
substitutions:
  name: sprinkler-controller
  friendly_name: Sprinkler Controller
  area: Laundry Room
  static_ip: 192.168.137.6

packages:
  - !include common/base.yml
  - !include common/wifi.yml
  - !include common/time.yml

wifi:
  use_address: 192.168.0.118

esp32:
  variant: esp32
  framework:
    type: esp-idf

status_led:
  pin:
    number: 23

sprinkler:
  - id: sprinkler_controller
    main_switch: Main
    auto_advance_switch: Auto Advance
    reverse_switch: Reverse
    multiplier_number: Multiplier
    repeat_number: Repeat
    valve_overlap: 5s
    valves:
      - valve_switch: Valve 1
        enable_switch: Enable Valve 1
        run_duration_number: Valve 1 Run Duration
        valve_switch_id: relay_1
      - valve_switch: Valve 2
        enable_switch: Enable Valve 2
        run_duration_number: Valve 2 Run Duration
        valve_switch_id: relay_2
      - valve_switch: Valve 3
        enable_switch: Enable Valve 3
        run_duration_number: Valve 3 Run Duration
        valve_switch_id: relay_3
      - valve_switch: Valve 4
        enable_switch: Enable Valve 4
        run_duration_number: Valve 4 Run Duration
        valve_switch_id: relay_4

switch:
  - platform: gpio
    pin: GPIO32
    name: Relay 1
    id: relay_1

  - platform: gpio
    pin: GPIO33
    name: Relay 2
    id: relay_2

  - platform: gpio
    pin: GPIO25
    name: Relay 3
    id: relay_3

  - platform: gpio
    pin: GPIO26
    name: Relay 4
    id: relay_4

  - platform: gpio
    pin: GPIO27
    name: Relay 5
    id: relay_5

  - platform: gpio
    pin: GPIO14
    name: Relay 6
    id: relay_6

  - platform: gpio
    pin: GPIO12
    name: Relay 7
    id: relay_7

  - platform: gpio
    pin: GPIO13
    name: Relay 8
    id: relay_8
