# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

dotenv: [.env]

tasks:
  default: task --list-all
  compile:all:
    deps:
      - compile:basement-string-lights
      - compile:garage-relay
      - compile:livingroom-lamp
      - compile:master-bedroom-switches
      - compile:washing-machine-outlet

  compile:*:
    vars:
      DEVICE: '{{index .MATCH 0}}'
    sources: [./secrets.yaml, './{{.DEVICE}}.yml']
    generates: ['./.esphome/build/{{.DEVICE}}/']
    cmd: esphome compile ./{{.DEVICE}}.yml
